defmodule MyXDR.IntUnion do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `IntUnion` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{
    Int,
    Error,
    MultiList
  }

  @arms %{
    0 => Error,
    1 => MultiList
  }

  @type int_union ::
          Error.t()
          | MultiList.t()

  @type t :: %__MODULE__{int_union: int_union(), type: Int.t()}

  defstruct [:int_union, :type]

  @spec new(int_union :: int_union(), type :: Int.t()) :: t()
  def new(int_union, %Int{} = type), do: %__MODULE__{int_union: int_union, type: type}

  @impl true
  def encode_xdr(%__MODULE__{int_union: int_union, type: type}) do
    type
    |> XDR.Union.new(@arms, int_union)
    |> XDR.Union.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{int_union: int_union, type: type}) do
    type
    |> XDR.Union.new(@arms, int_union)
    |> XDR.Union.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ union_spec())

  def decode_xdr(bytes, spec) do
    case XDR.Union.decode_xdr(bytes, spec) do
      {:ok, {{type, int_union}, rest}} -> {:ok, {new(int_union, type), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ union_spec())

  def decode_xdr!(bytes, spec) do
    {{type, int_union}, rest} = XDR.Union.decode_xdr!(bytes, spec)
    {new(int_union, type), rest}
  end

  @spec union_spec() :: XDR.Union.t()
  defp union_spec do
    0
    |> Int.new()
    |> XDR.Union.new(@arms)
  end
end
