defmodule MyXDR.MyUnion do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `MyUnion` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{
    UnionKey,
    MyUnionOne,
    MyUnionTwo,
    Void
  }

  @arms [
    ONE: MyUnionOne,
    TWO: MyUnionTwo,
    OFFER: Void
  ]

  @type my_union ::
          MyUnionOne.t()
          | MyUnionTwo.t()
          | Void.t()

  @type t :: %__MODULE__{my_union: my_union(), type: UnionKey.t()}

  defstruct [:my_union, :type]

  @spec new(my_union :: my_union(), type :: UnionKey.t()) :: t()
  def new(my_union, %UnionKey{} = type), do: %__MODULE__{my_union: my_union, type: type}

  @impl true
  def encode_xdr(%__MODULE__{my_union: my_union, type: type}) do
    type
    |> XDR.Union.new(@arms, my_union)
    |> XDR.Union.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{my_union: my_union, type: type}) do
    type
    |> XDR.Union.new(@arms, my_union)
    |> XDR.Union.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ union_spec())

  def decode_xdr(bytes, spec) do
    case XDR.Union.decode_xdr(bytes, spec) do
      {:ok, {{type, my_union}, rest}} -> {:ok, {new(my_union, type), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ union_spec())

  def decode_xdr!(bytes, spec) do
    {{type, my_union}, rest} = XDR.Union.decode_xdr!(bytes, spec)
    {new(my_union, type), rest}
  end

  @spec union_spec() :: XDR.Union.t()
  defp union_spec do
    nil
    |> UnionKey.new()
    |> XDR.Union.new(@arms)
  end
end
