defmodule MyXDR.ConstFOO do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `ConstFOO` type.
  """

  @behaviour XDR.Declaration

  @spec const :: integer()
  def const, do: 1244
end
