defmodule MyXDR.Int4 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `Int4` type.
  """

  @behaviour XDR.Declaration

end
