defmodule MyXDR.OptHash1 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptHash1` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Hash

  @optional_spec XDR.Optional.new(Hash)

  @type opt_hash1 :: Hash.t() | nil

  @type t :: %__MODULE__{opt_hash1: opt_hash1()}

  defstruct [:opt_hash1]

  @spec new(opt_hash1 :: opt_hash1()) :: t()
  def new(opt_hash1 \\ nil), do: %__MODULE__{opt_hash1: opt_hash1}

  @impl true
  def encode_xdr(%__MODULE__{opt_hash1: opt_hash1}) do
    opt_hash1
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{opt_hash1: opt_hash1}) do
    opt_hash1
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: opt_hash1}, rest}} -> {:ok, {new(opt_hash1), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    {%XDR.Optional{identifier: opt_hash1}, rest} = XDR.Optional.decode_xdr!(bytes)
    {new(opt_hash1), rest}
    {nil, rest} -> {new(), rest}
  end
end
