defmodule MyXDR.OptHash1 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptHash1` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.OptionalHash

  @optional_spec XDR.Optional.new(OptionalHash)

  @type optional_hash :: OptionalHash.t() | nil

  @type t :: %__MODULE__{optional_hash: optional_hash()}

  defstruct [:optional_hash]

  @spec new(optional_hash :: optional_hash()) :: t()
  def new(optional_hash \\ nil), do: %__MODULE__{optional_hash: optional_hash}

  @impl true
  def encode_xdr(%__MODULE__{optional_hash: optional_hash}) do
    optional_hash
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{optional_hash: optional_hash}) do
    optional_hash
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: optional_hash}, rest}} -> {:ok, {new(optional_hash), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    case XDR.Optional.decode_xdr!(bytes, optional_spec) do
      {%XDR.Optional{type: optional_hash}, rest} -> {new(optional_hash), rest}
      {nil, rest} -> {new(), rest}
    end
  end

end
