defmodule MyXDR.OptionalOpthash1 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalOpthash1` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Opthash1

  @optional_spec XDR.Optional.new(Opthash1)

  @type opthash1 :: Opthash1.t() | nil

  @type t :: %__MODULE__{opthash1: opthash1()}

  defstruct [:opthash1]

  @spec new(opthash1 :: opthash1()) :: t()
  def new(opthash1 \\ nil), do: %__MODULE__{opthash1: opthash1}

  @impl true
  def encode_xdr(%__MODULE__{opthash1: opthash1}) do
    opthash1
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{opthash1: opthash1}) do
    opthash1
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: opthash1}, rest}} -> {:ok, {new(opthash1), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    {%XDR.Optional{identifier: opthash1}, rest} = XDR.Optional.decode_xdr!(bytes)
    {new(opthash1), rest}
    {nil, rest} -> {new(), rest}
  end
end
