defmodule MyXDR.OptionalOpthash2 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalOpthash2` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Opthash2

  @optional_spec XDR.Optional.new(Opthash2)

  @type opthash2 :: Opthash2.t() | nil

  @type t :: %__MODULE__{opthash2: opthash2()}

  defstruct [:opthash2]

  @spec new(opthash2 :: opthash2()) :: t()
  def new(opthash2 \\ nil), do: %__MODULE__{opthash2: opthash2}

  @impl true
  def encode_xdr(%__MODULE__{opthash2: opthash2}) do
    opthash2
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{opthash2: opthash2}) do
    opthash2
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: opthash2}, rest}} -> {:ok, {new(opthash2), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    {%XDR.Optional{identifier: opthash2}, rest} = XDR.Optional.decode_xdr!(bytes)
    {new(opthash2), rest}
    {nil, rest} -> {new(), rest}
  end
end
