defmodule MyXDR.TestArray2 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TestArray2` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Int

  @max_length 1

  @array_type Int

  @array_spec %{type: @array_type, max_length: @max_length}

  @type t :: %__MODULE__{ints: list(Int.t())}

  defstruct [:ints]

  @spec new(ints :: list(Int.t())) :: t()
  def new(ints), do: %__MODULE__{ints: ints}

  @impl true
  def encode_xdr(%__MODULE__{ints: ints}) do
    ints
    |> XDR.VariableArray.new(@array_type, @max_length)
    |> XDR.VariableArray.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ints: ints}) do
    ints
    |> XDR.VariableArray.new(@array_type, @max_length)
    |> XDR.VariableArray.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @array_spec)

  def decode_xdr(bytes, spec) do
    case XDR.VariableArray.decode_xdr(bytes, spec) do
      {:ok, {ints, rest}} -> {:ok, {new(ints), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @array_spec)

  def decode_xdr!(bytes, spec) do
    {ints, rest} = XDR.VariableArray.decode_xdr!(bytes, spec)
    {new(ints), rest}
  end
end
