defmodule MyXDR.TestArray do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TestArray` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Int

  @length 1

  @array_type Int

  @array_spec %{type: @array_type, length: @length}

  @type t :: %__MODULE__{ints: list(Int.t())}

  defstruct [:ints]

  @spec new(ints :: list(Int.t())) :: t()
  def new(ints), do: %__MODULE__{ints: ints}

  @impl true
  def encode_xdr(%__MODULE__{ints: ints}) do
    ints
    |> XDR.FixedArray.new(@array_type, @length)
    |> XDR.FixedArray.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ints: ints}) do
    ints
    |> XDR.FixedArray.new(@array_type, @length)
    |> XDR.FixedArray.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @array_spec)

  def decode_xdr(bytes, spec) do
    case XDR.FixedArray.decode_xdr(bytes, spec) do
      {:ok, {ints, rest}} -> {:ok, {new(ints), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @array_spec)

  def decode_xdr!(bytes, spec) do
    {ints, rest} = XDR.FixedArray.decode_xdr!(bytes, spec)
    {new(ints), rest}
  end
end
